name: Specialization
version: '0.0.0.1'
main: com.minecraftcivilizations.specialization.OpenLab
api-version: '1.20'
depend:
  - ProtocolLib
authors: [ DNFneca ]
description: Lyphea

commands:
  simulatehit:
    description: Simulate a combat hit for testing.
    usage: /simulatehit
    permission: specialization.simulatehit